---
- name: "{{ playbook_dir | basename }}"
  hosts: localhost
  remote_user:
  gather_facts: yes
  vars:
    status: "{{ ansible_local[stats_file_name]['status'] | default('0') }}"
  force_handlers: no
  pre_tasks:
    - name: update ansible facts
      setup:
        gather_subset:
          - "all"

    - when: status == '0'
      block:
        - import_role:
            name: pre_roles/common
          tags:
            - pr_r_common
        - meta: flush_handlers

  tasks:
    - when: status == '0'
      block:
        - import_role:
            name: alias_profile
          tags:
            - r_alias_profile
        - meta: flush_handlers

        - import_role:
            name: ascii_banner
          tags:
            - r_ascii_banner
        - meta: flush_handlers

        - import_role:
            name: base_kparams
          tags:
            - r_base_kparams
        - meta: flush_handlers

        - import_role:
            name: base_kparams_cron
          tags:
            - r_base_kparams_cron
        - meta: flush_handlers

        - import_role:
            name: base_rlimits
          tags:
            - base_rlimits
        - meta: flush_handlers

        - import_role:
            name: chrony
          tags:
            - r_chrony
        - meta: flush_handlers

        - import_role:
            name: history
          tags:
            - r_history
        - meta: flush_handlers

        - import_role:
            name: pip
          tags:
            - r_pip
        - meta: flush_handlers

        - import_role:
            name: prompt
          tags:
            - r_prompt
        - meta: flush_handlers

        - import_role:
            name: sys_preinst
          tags:
            - r_sys_preinst
        - meta: flush_handlers

        - import_role:
            name: users
          tags:
            - r_prompt
        - meta: flush_handlers

        - import_role:
            name: vim
          tags:
            - r_vim
        - meta: flush_handlers

  post_tasks:
    - when: status == '0'
      block:
        - import_role:
            name: post_roles/common
          tags:
            - po_r_common
        - meta: flush_handlers
